
services:
  offres-service:
    build:
      context: ./offres-service
    ports:
      - "8001:80"
    environment:
      - DB_HOST=db
      - DB_DATABASE=offres_db
      - DB_USERNAME=root
      - DB_PASSWORD=  
    depends_on:
      - db

  candidatures-service:
    build:
      context: ./candidatures-service
    ports:
      - "8002:80"
    environment:
      - DB_HOST=db
      - DB_DATABASE=candidatures_db
      - DB_USERNAME=root
      - DB_PASSWORD=  
    depends_on:
      - db

  utilisateurs-service:
    build:
      context: ./utilisateurs-service
    ports:
      - "8003:80"
    environment:
      - DB_HOST=db
      - DB_DATABASE=utilisateurs_db
      - DB_USERNAME=root
      - DB_PASSWORD=  
    depends_on:
      - db

  db:
    image: mysql:9.1
    environment:
      MYSQL_ROOT_PASSWORD:   
      MYSQL_DATABASE: default_db  
      MYSQL_USER: root
      MYSQL_PASSWORD:   
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql  

volumes:
  mysql-data:
